@startuml

class Biblioteca {
  +agregarSocio(socio: Socio): void
  +exportarSocios(): String
}

class Socio {
  -nombre: String
  -legajo: String
  -email: String
}

class VoorheesExporter {
  +exportar(socio: Socio): String
  +exportar(socios: List<Socio>): String
}

Biblioteca --> "*" Socio: "socios"
Biblioteca --> VoorheesExporter: "exporter"


@enduml